### PR TITLE
Update pt_BR line menu context

### PR DESCRIPTION
**Pull request by maisondasilva**
Fix new line menu context

## Description

Resolves: #issue_number

### CODE REVIEW

**Comment by maisondasilva** [comment]
@XFox111

**Review by XFox111 — APPROVED** [review]

**Comment by XFox111** [comment]
LGTM. Btw, next time you create a PR make sure you've made it against `next`. There's some automation going on that prevents flooding main with small commits

**Comment by maisondasilva** [comment]
@XFox111 Yes, as I thought you were already preparing to release the version I just sent the pull without looking at the details, Thanks for that!

**Comment by XFox111** [comment]
Yeah, don't worry :) It's not a big deal, just reduces the workload

**Pull request merged**
